### ISSUE TITLE
warden (devise) compatibility

### ISSUE THREAD

**Issue by clyfe** [vhochstein/render_component#1]
If render_component is used alongside with devise (or warden) it can lead to `no method error "authenticate!" for nil:NilClass`.
This is due that the rendered controller will try to enforce authentication looking into the `request.env['warden']` object to call `authenticate!` on it.

To fix this particular case we need to add on line 121 of

```
# render_component/lib/components.rb +121
request_env["warden"] = request.env['warden'] if request.env['warden']
```

I think that for a more broad compatibilty, more variables from the `request.env` should be copied.

**Comment by vhochstein** [comment]
Take a look at this commit: https://github.com/vhochstein/render_component/commit/ec065ed6a3da8843e87f5afd7dfb9936e759047d

Should already be there

**Comment by clyfe** [comment]
Yes, that is good, thank you
