### ISSUE TITLE
rails 4.1

### ISSUE THREAD

**Issue by mathieujobin** [vhochstein/render_component#7]
it looks like this fork has the most recent version of this gem.. supporting rails 3.0
quickly, I could not find a more active one... but let me know if you think I am wrong...

I am actually in the progress of porting an rails 1.1.6 application to rails 4.1.4
which is using components extensively... is there a better solution nowadays? or should I attempt to create yet another fork of this attempting to make it work with 4.1 ?

thanks

**Comment by vhochstein** [comment]
Not sure if there is a more current version/fork. This one is working up to rails  3.2
So far I do not have a project running on rails 4.x, therefore I have nt started the migration.
If you would like to give it a try, please feel free.

**Comment by mathieujobin** [comment]
I have ... its working almost as it is .. I disabled the hook around flash.
it was turning my session['flash'] into a String object that looked to be an inspect call.
weird... anyway

I forked the active_scaffolding one, which was almost like yours, but using regular gemspec instead of jewelry stuff I dont know anything about.
